import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./ui/Header";
import Footer from "./components/footer/Footer";
import TanstackProvider from "./TanstackProvider";

const inter = Poppins({
  subsets: ["latin"],
  style: ["normal", "italic"],
  // weight: ["100", "300", "400", "500", "700", "900"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <Header />
          <main className=" min-h-dvh text-slate-900">{children}</main>
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
